### ISSUE TITLE
Just Thanks !!

### ISSUE THREAD

**Issue by axgkl** [robinjia/easy-upload#1]
exactly what I was looking for - and not more - except a feature I did not even know I wanted ( the perf patch).

Works in py3  as well after 2to3 btw.

Cheers!

**Comment by axgkl** [comment]
Add on: At least on python 3 I had to change in `util.py`:
```
dt = numpy.dtype('Q')  # was '<Q8' 
```
Perf. improvement is amazing through numpy:
150MB test file via

- scp (benchmark): 11sec
- w/o numpy:      "Took 36.927 seconds"
- with the patch: "Took 13.055 seconds"

clap. clap.

**Comment by robinjia** [comment]
Thank you so much for the note! I'm glad you're finding this useful :)
